name: Code Quality
on: [push, pull_request]
jobs:
  container:
    strategy:
      matrix:
        go-version: [1.13.x]
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Code Climate
      uses: paambaati/codeclimate-action@v2.2.1